"output":
    "
    stderr:\n
    start to close fds...\n
    Traceback (most recent call last):\n
        File \"/usr/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n
        \"__main__\", mod_spec)\n
        File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n
        exec(code, run_globals)\n
            File \"638b18e58d38157ab2efe7a7.py36/__main__.py\", line 87, in <module>\n
            File \"638b18e58d38157ab2efe7a7.py36/__main__.py\", line 14, in obs2response\n
            File \"/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py\", line 889, in _call_impl\n
            result = self.forward(*input, **kwargs)\n
            File \"638b18e58d38157ab2efe7a7.py36/model.py\", line 82, in forward\n
            File \"/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py\", line 889, in _call_impl\n
            result = self.forward(*input, **kwargs)\n
            File \"638b18e58d38157ab2efe7a7.py36/model.py\", line 45, in forward\n
            File \"/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py\", line 889, in _call_impl\n
            result = self.forward(*input, **kwargs)\n
            File \"/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py\", line 399, in forward\n
            return self._conv_forward(input, self.weight, self.bias)\n
            File \"/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py\", line 396, in _conv_forward\n
            self.padding, self.dilation, self.groups)\nRuntimeError: Expected 4-dimensional input for 4-dimensional weight [256, 133, 3, 3], but got 3-dimensional input of size [133, 8, 8] instead\n\n\n
    stdout:
    \nPASS\n>>>BOTZONE_REQUEST_KEEP_RUNNING<<<\nPASS\n>>>BOTZONE_REQUEST_KEEP_RUNNING<<<\nPASS\n>>>BOTZONE_REQUEST_KEEP_RUNNING<<<\n
    ",